schemas/access/bot-1.yml, schemas/access/permission-1.yml, schemas/access/role-1.yml, schemas/access/user-1.yml, schemas/app-sre/app-1.yml, schemas/metaschema-1.json, schemas/openshift/cluster-1.yml
This MR includes two changes:
- It turns out that draft04 does not support the keyword `const` so it wasn't doing anything. It has been replaced with a single element `enum` list.
- Certain types of permissions require specific associated attributes. These have been modelled into permission-1.yml schema.
=> Schema for permissions

src/db.ts, src/schema.ts, src/server.ts
Before this fix the server was unusable after doing `/reload`,
displaying this error:
```
TypeError: Cannot read property 'size' of undefined
at app.use (webpack:///./src/server.ts?:22:86)
at Layer.handle [as handle_request] (webpack:///./node_modules/express/lib/router/layer.js?:95:5)
at trim_prefix (webpack:///./node_modules/express/lib/router/index.js?:317:13)
at eval (webpack:///./node_modules/express/lib/router/index.js?:284:7)
at Function.process_params (webpack:///./node_modules/express/lib/router/index.js?:335:12)
at next (webpack:///./node_modules/express/lib/router/index.js?:275:10)
at expressInit (webpack:///./node_modules/express/lib/middleware/init.js?:40:5)
at Layer.handle [as handle_request] (webpack:///./node_modules/express/lib/router/layer.js?:95:5)
at trim_prefix …
```
=> bug: fix reload

README.md
Fix the absence of newline escape, which caused the qontract-bundler command to run separately and fail
=> Fix bundle creation command

assets/schema.yml, assets/schemas/app-sre/app-1.yml
This adds a serviceDocs property to the app schema. The serviceDocs property is a list of string that is used to reference service-related documentation.
=> Add serviceDocs to app schema

src/schema.ts
This PR defines the graphql object types functions, solving the problem of being able to define graphql object types that depend on other graphql object types that haven't been defined yet.
For example:
```yaml
- name: Bot_v1
fields:
- { name: name, type: string, isRequired: true }
- { name: owner, type: User_v1 }
- name: User_v1
fields:
- { name: name, type: string, isRequired: true }
```
This used to fail, because Bot_v1 was referencing a type that wasn't yet defined. This now works.
=> support lazy objectype evaluation

README.md
If someone is reading from top-bottom, its hard to notice that you need to create the bundle BEFORE you attempt to run the GraphQL server. 
This is a minor fix but hopefully avoids confusion for future developers.
=> Restructure readme, create bundle before run

package.json, src/server.ts, yarn.lock
Add a bunch of metrics for qontract server, including: 
- NodeJS runtime metrics
- Count of datafiles currently known to qontract-server per schema type
Full list of metrics: 
```
qontract_server_nodejs_external_memory_bytes{}
qontract_server_nodejs_heap_size_used_bytes{}
qontract_server_process_resident_memory_bytes{}
qontract_server_process_cpu_system_seconds_total{}
qontract_server_process_heap_bytes{}
qontract_server_process_start_time_seconds{}
qontract_server_nodejs_heap_space_size_available_bytes{}
qontract_server_nodejs_heap_space_size_total_bytes{}
qontract_server_nodejs_heap_space_size_used_bytes{}
qontract_server_process_open_fds{}
qontract_server_process_virtual_memory_bytes{}
scrape_samples_post_metric_relabeling{}
qontract_server_nodejs_active_handles_total{} …
```
=> Add basic metrics for qontract-server

Makefile
This updates the Makefile to run the docker container interactively and with pseudo-tty so it can catch a Ctrl-C / SIGINT from the host which is especially useful when running locally
=> Makefile: run container interactively

package.json, src/server.ts, yarn.lock
Replaces https://github.com/app-sre/qontract-server/pull/71
Adds `http_request_duration_seconds` metrics (`bucket`, `sum` and `count`).
Example of metrics that have been added:
```
http_request_duration_seconds_bucket{le="0.003",status_code="2xx",method="POST",path="/graphql"} 0
http_request_duration_seconds_bucket{le="0.03",status_code="2xx",method="POST",path="/graphql"} 2
http_request_duration_seconds_bucket{le="0.1",status_code="2xx",method="POST",path="/graphql"} 12
http_request_duration_seconds_bucket{le="0.3",status_code="2xx",method="POST",path="/graphql"} 12
http_request_duration_seconds_bucket{le="1.5",status_code="2xx",method="POST",path="/graphql"} 12
http_request_duration_seconds_bucket{le="10",status_code="2xx",method="POST",path="/graphql"} 12 …
```
=> adds latency metrics

src/schema.ts, src/server.ts, test/schemas/cluster.test.ts, test/server.test.ts
The current response payload that this server is implementing only contains `data` and `errors`:
```json
{
"data": ...,
"errors": ...,
}
```
We now require a complete list of schemas that each query has traversed, to
identify schema dependencies per query.
The GraphQL spec [1] supports creating extensions (plugins) to add additional custom
data to the response payload.
This PR includes a plugin that adds an additional field `extensions` to the response payload:
```json
{
"data": ...,
"errors": ...,
"extensions": {
"schemas": ["/schema1.yaml",...]
}
}
```
[1]: https://spec.graphql.org/June2018/#sec-Response-Format
=> Adds an extension that returns all traversed schemas

package.json, src/db.ts, src/logger.ts, src/server.ts, yarn.lock
Previously logging was naively using `console.log`. We want to migrate to a better logging framework to be able to manage logging levels and to add timestamps.
This PR migrates to https://github.com/winstonjs/winston for the logging messages.
This is an example run:
```
$ node ./dist/main-bundle.js
2020-10-29T10:33:57.591Z INFO: Running at http://localhost:4000/graphql
2020-10-29T10:34:03.485Z INFO: skipping reload, data already loaded
2020-10-29T10:34:19.877Z INFO: bundle loaded: 6e84c88f5b4debcf26b393fd3ace05729cf39a8a191e1ba9f30a5c392b906b5a
2020-10-29T10:34:40.496Z INFO: removing expired bundle: e94972914f41a3ecef5f2b83903c2747da3ee83ba41cc19730c0966b3681f669
2020-10-29T10:34:40.593Z INFO: bundle loaded: 0954998a34537c38fc6ce9e73f5b1664ab6d10c3e6d70ec0a061b3042ab21743
```
This PR also …
=> better logging

src/schema.ts, src/server.ts, test/server.data.json, test/server.test.ts
This PR introduces a new feature to allow querying for specific fields in the schema. This is useful because otherwise the filtering needs to happen in the client side wasting bandwidth.
The GraphQL schema defined in the bundle now allows users to mark fields with the `isSearchable: true` attribute. This will make the specific attribute queryable.
For example, with this schema:
```yaml
datafile: /access/role-1.yml
name: Role_v1
fields:
- name: name
type: string
isRequired: true
isSearchable: true
- ...
```
It will be possible to run the following query: `{ role_v1(name: "<name>") { path, name}}`.
Note that querying for the `path` attribute is implicitely supported for all datafiles (as it's a mandatory attribute).
=> APPSRE-1045: query objects using arbitrary arguments

pr_check.sh
Now that Travis CI was removed, we want to use the default pr_check.sh as part of the build
Adding pr_check.sh 
* No need to do `yarn install` because the image has yarn built in according to the Dockerfile.
Ran `qontract-reconcile --config config.debug.toml --dry-run --log-level DEBUG jenkins-job-builder` locally and it passed.
=> APPSRE-3783: Add pr_check.sh that contains the removed TravisCI yarn commands.

Dockerfiletest, pr_check.sh
Instead of directly in Jenkins executor, use container to install and run yarn for pr_check.
=> Use container to install and run yarn instead.

Makefile, README.md
part of https://issues.redhat.com/browse/APPSRE-3946
this PR changes the way we develop, by changing the location of schemas from app-interface to qontract-schemas.
=> work with qontract-schemas

openshift/app-interface.yaml
failure-domain.beta.kubernetes.io/zone is deprecated from 1.17
=> Use non-deprecated topology keys

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
As part of [APPSRE-3940](https://issues.redhat.com/browse/APPSRE-3940), move the Grafana dashboard configmap file to the upstream repository. From there, I'll make changes to App Interface to use this file from upstream and delete the existing on in AI.
=> Move Grafana Dashboard Upstream

src/db.ts, src/server.ts, test/multishas/multishas.test.ts, test/schemas/schemas.test.ts, test/server.test.ts
if the env variable `INIT_DISK_BUNDLES` is given, it is processed as CSV list of bundle paths to be loaded into the bundle cache.
this is a feature that will be used mostly during PR checks. having a qontract-server running with two bundles, enables us to compute rich diffs between bundles. this PR will be followed up by one that introduces a qontract-server endpoint `/diff/$sha/$sha` that will return the differences from one bundle to another (the change of an MR). we do something similar right now during app-interface pr checks already but based on `git diff`, which lacks context. e.g. if a resource is changed, what datafile does it belong to and what shard of what integration do we need to run during a PR check.
alternatively we could also start the q-s with one bundle, wait for it to …
=> allow loading multiple fs bundles on startup

package.json, src/db.ts, src/server.ts, test/diff/diff.test.ts, test/diff/new.data.json, test/diff/old.data.json, test/schemas/schemas.test.ts, yarn.lock
provide a `diff/$old_bundle/$new_bundle` endpoint on qontract-server that provides detailed diffs between two bundles currently present in the qontract-server
this endpoint will be used during PR checks to find involved schemas for an app-interface MR. the diff endpoint needs to expose diffs for resource files as well along with their relation to the referencing data file. this way, we don't have to guess the involved schemas anymore during PR checks but have an explicit and correct way to find them all.
The endpoint returns a list of changes with the following fields
* datafilepath - the path of the data file that changed
* datafileschema - the schema of the datafile that changed
* resourcepath - the path of the resource that changed in the context of the datafile
* action: 
** `E` if a …
=> bundle diff endpoint

README.md, src/db.ts, test/diff/diff.test.ts, test/schemas/schemas.test.ts, test/server.test.ts
renamed `INIT_DISK_BUNDLES` to `INIT_BUNDLES` and allow pre-populating a qontract-server with bundles from fs or s3
`INIT_BUNDLES` is a CSV of bundle references of the following formats
* fs://path/to/bundle
* s3://bundle-key
The s3 flavour relies on the `AWS_*` env variables to specify the bucket and configure authentication. the specified `bundle-key` is used as `AWS_S3_KEY`.
The bundles listed in `INIT_BUNDLE` can come from different sources and are added to the `qontract-server` in the order they are specified. This means that the bundle listed last is also the one returned by the `/sha256` endpoint.
This change will allow running a local `qontract-server` during app-interface PR-checks and preloading it with the freshly built bundle from the MR branch as well as the bundle …
=> INIT_BUNDLES from s3

src/db.ts, src/schema.ts, test/schemas/schemas.data.with.graphql.schema.header.json, test/schemas/schemas.test.ts
This change allows qontract-server to run with two different bundle format. 
This is part of the design doc https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/40672
=> APPSRE-2694: use graphql.confs for schema

src/schema.ts, test/resourceref/data.json, test/resourceref/resourceref.test.ts
resource files are somehow detached from our regular graphql types. they are just references as a path and it is up to the respective integration to fetch the content of such a resource with a dedicated query. this consumes a lot of time during integration runs and pr checks, because such resources are fetched one by one (see terraform-resources defaults or jjb config_path).
`isResource`field definition enhanced with `resolveResource: true` will be queryable as graphql type `Resource_v1`
schema.yml
```yaml
- name: JenkinsConfig_v1
fields:
...
- { name: config_path, type: string, isResource: true, resolveResource: true }
```
query
```
{
jenkins_configs: jenkins_configs_v1 {
name
...
type
config
config_path {
content
sha256sum
}
}
}
```
ref: https://issues.redhat.com/browse/APPSRE-5950 …
=> resource reference resolver

Dockerfile, Dockerfiletest
The primary goal of this PR was to move the image to UBI 8
The PR also uses the NodeJS flavor of the UBI image. While researching this I realized the version we are currently using (10.x) has reached end of life over a year ago. 
Nodejs 10 and 12 have both reached end of life. Nodejs 14 will reach end of life in less than a year. NodeJS 16 is the current LTS version.
Using the NodeJS flavor also simplified the Dockerfile and the packages that were required
I've done tests locally
- qontract-server starts fine
- the `/graphql` endpoint works and running queries workm and return expected results
- the `/reload` endpoint worked
This also closes #84
=> Update image from centos:7 to ubi8 and nodejs 10 to 16

SCHEMA.md, src/schema.ts, test/synthetic/data.json, test/synthetic/synthetic.test.ts
the `subAttr` field of a synthetic declaration is used as a foreign key to define the backreference relation to another schema.
this PR enables the `subAttr` field to declare this relation not only to top level fields of the referenced schema but also nested fields, using `.` (dot) as a separator for nesting levels.
Example
```
- name: StatusPage_v1
fields:
- name: components
type: StatusPageComponent_v1
isList: true
synthetic:
schema: /dependencies/status-page-component-1.yml
subAttr: some.path.to.a.page
```
Will be used in https://github.com/app-sre/qontract-schemas/pull/189 to backreference between maintenances and the statuspage components that participate.
=> synthetic subAttr referencing nested fields

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
kube_pod_container_resource_limits_memory_bytes is now
kube_pod_container_resource_limits and
=> Fix grafana dashboard memory panel

openshift/app-interface.yaml
Continuation of migration effort to `Deployment` workload. This change will begin routing traffic to both workloads so that new `Deployment` can be verified.
Ticket: https://issues.redhat.com/browse/APPSRE-5932
=> Target both DC and D workloads

openshift/app-interface.yaml
This reverts commit 0326a16b617f71b40bf1d2ab62f57ae0717e738a.
Monitoring of `sd-app-sre-reconcile-stage`'s consistent output since merge has reduced confidence in using this approach.
=> Revert "target both DC and D workloads (#155)"

src/server.ts, test/diff/diff.test.ts
javascript diffing capabilities are limited and some corner cases can't be covered to detect proper structural diffs, e.g. adding or removing array elements in places other than the end of the array yields a lot of fake changes.
therefore the diff endpoint output has been simplified. it does not report fine grained changes for datafiles and resources anymore but instead exposes only the changes files with some metadata. it is up to the user of the diff endpoint to look for specific changes within the old and new state of a datafile or resource.
this is a breaking change for the endpoint because the change path details have been removed. but since this endpoint is not in use yet, changing it is legit.
in python the deep-diff library is capable to detect all those changes in a stable way …
=> simplify diff exposure between two bundles

src/server.ts
the cached datafileSchemas were not removed when its bundle expired.
=> fix memory leak when removing expired bundles

src/schema.ts, src/server.ts
* objectTypes and objectInterfaces were not cleaned up on bundle expiration - this changes removes those cached objects on bundle expiration
* unnecessary interface resolver functions were created - this change only creates them for either types that really have interfaces or are a datafile and get the dynamic DatafileObject_v1 interface assigned
=> fix more memory leaks and avoid unnecessary interface resolver functions

src/schema.ts
this change renders lists non-nullable if `isRequired: true` is defined. this relates more the the `required` semantics of `jsonschema`. additonally, list elements will not be nullable, which is consistent with the way AppSRE uses jsonschema in `qontract-schema`
https://json-schema.org/understanding-json-schema/reference/object.html#required-properties
the `qenerate` generated gql dataclasses would reflect such a change as follows
```python
-    saas_files: Optional[list[Optional[SaasFileV2]]] = Field(..., alias="saasFiles")
+    saas_files: Optional[list[SaasFileV2]] = Field(..., alias="saasFiles")
```
```python
-    saas_files: Optional[list[SaasFileV2]] = Field(..., alias="saasFiles")
+    saas_files: list[SaasFileV2] = Field(..., alias="saasFiles")
```
Part of …
=> non-nullable lists on isRequired

SCHEMA.md, src/schema.ts, test/synthetic/data.json, test/synthetic/synthetic.test.ts
the `subAttr` field of a synthetic declaration is used as a foreign key to define the backreference relation to another schema.
this PR enables the `subAttr` field to declare this relation not only to top level fields of the referenced schema but also nested fields, using `.` (dot) as a separator for nesting levels.
Example
```
- name: StatusPage_v1
fields:
- name: components
type: StatusPageComponent_v1
isList: true
synthetic:
schema: /dependencies/status-page-component-1.yml
subAttr: some.path.to.a.page
```
Will be used in https://github.com/app-sre/qontract-schemas/pull/189 to backreference between maintenances and the statuspage components that participate.
this feature was once introduced in #150 and reverted in #159 because it was (wrongly) suspected to be the culprit of …
=> synthetic subAttr referencing nested fields, 2nd attempt

openshift/app-interface.yaml
We witness a lot of unnecessary throttling - we decided to remove limits for now.
=> Remove CPU limits

openshift/app-interface.yaml
Following #166
CPU limits are proving to be harmful on q-s, throttling while CPU is not being maxed out.
=> Remove all remaining CPU limits

openshift/app-interface.yaml
qontract-server freezes while reloading the bundling as parsing json is a blocking operation. While we fix that, we will need to increase the waiting times in the probes to avoid continuous restarts which are quite bad since data is stored in memory.
=> Increase waiting times in probes

openshift/app-interface.yaml
This is part 1 of 2 to migrate qontract-server to a `Deployment` workload. 
This change will provision a `Deployment` with identical config to the existing DC but without adjusting the service selectors to target it. I.E, this workload will not receive any traffic until part 2 (alter services to select both workloads).
context from original approval: https://github.com/app-sre/qontract-server/pull/153
ticket: https://issues.redhat.com/browse/APPSRE-5932
=> provision deployment workload alongside deploymentconfig

openshift/app-interface.yaml
This will "fan-in" the app-interface service and route 100% of traffic to new `Deployment` workload
follow up to https://github.com/app-sre/qontract-server/pull/173
=> target deployment exclusively

openshift/app-interface.yaml
Addresses `livenessProbe.httpGet.port: Invalid value: "s3-reloader-metrics": must be no more than 15 characters`
=> rename to comply with max character limit of 15

README.md, src/server.ts, test/diff/diff.test.ts
to support some advanced change-type processes in qontract-reconciles change-owner integration (hopping multiple files to expand ownership for reusable change-types), a flavour of the existing diff endpoint is introduced to allow fetching diffs for an individual datafile or resourcefile.
`GET /diff/:sha/:another_sha/:filetype/:path` where `filetype` is `datafile` or `resourcefile`
=> diff endpoint for single file

openshift/app-interface.yaml
use v1 as the version for the PodDisruptionBudget since v1beta1 is not available anymore
=> openshift template PodDisruptionBudget version fix

.dockerignore
Update `.dockerignore` to avoid file permission issues like 
```
error An unexpected error occurred: "EACCES: permission denied, mkdir '/opt/app-root/node_modules/accepts'".
```
when running `make build` after `yarn install`.
Signed-off-by: Di Wang <dwan@redhat.com>
=> Update .dockerignore for file permissions

src/schema.ts, test/synthetic/data.json, test/synthetic/synthetic.test.ts
this implementation of the synthetic field resolver is not as clean as the previous one but runs a lot faster, which is crucial for the nodejs eventloop to not block.
* simple subAttr field - query apps and their namespaces via synthetic relation
* old implementation: 245-300ms
* new implementation: 164-195ms
* nested subAttr field - query saasfiles and their selfServiceRoles via the synthetic relation
* old implementation: 440-640ms
* new implementation: 320-375ms
this chagne is part of multiple approaches to unblock the nodejs event loop
=> reduce runtime of resolveSyntheticField

Makefile, package.json, src/db.ts, src/schema.ts, src/syntheticBackRefTrie.ts, src/types.ts, test/synthetic/data.json, test/synthetic/synthetic.test.ts
There are several improvements included in this change to further reduce CPU time spent on synthetic and datafileSchema resolver. Continue from https://github.com/app-sre/qontract-server/pull/172.
* Add a new field `datafilesBySchema` to `Bundle` as a fast lookup `datafiles` by `schema`, this is used in precompute synthetic field resolver and runtime check for datafileSchema fields.
* Add a new field `syntheticBackRefTrie` to `Bundle` to provide fast lookup `datafiles` by `(schema, subAttrs, path)`.
* Add a new task to debug typescript directly: `make debug`
Step by step CPU time on my local machine for nested subAttr field - query saasfiles and their selfServiceRoles via the synthetic relation:
1. old implementation: 749-811ms
2. [Precompute datafilesBySchema for …
=> Further improve performance of synthetic and datafileSchema resolver

Dockerfile, openshift/app-interface.yaml
* set default `NODE_OPTIONS` to `"--max-old-space-size=4096"` in Dockerfile
* set default `MAX_OLD_SPACE_SIZE` to `400` according to default memory limit `512Mi` in openshift template
=> Add NODE_OPTIONS env to container

openshift/app-interface.yaml
Fix to #193 
When deploying, getting the following error:
`[2023-03-02 06:04:58] [ERROR] [saasherder.py:_process_template:998] - [saas-qontract-server-int/qontract-server] https://github.com/app-sre/qontract-server/blob/master/openshift/app-interface.yaml: error processing template: [None]: error: failed to read input object (not a Template?): unable to decode "STDIN": json: cannot unmarshal number into Go struct field Parameter.parameters.value of type string`
Believe that is because that `400` is interpreted as a number rather than a string
=> Template change number to string

openshift/app-interface.yaml
Following https://docs.openshift.com/container-platform/4.12/openshift_images/using-templates.html#templates-writing-parameters_using-templates, switch to just a string param as:
> When using the ${{PARAMETER_NAME}} syntax only a single parameter reference is allowed and leading and trailing characters are not permitted. The resulting value is unquoted unless, after substitution is performed, the result is not a valid JSON object. If the result is not a valid JSON value, the resulting value is quoted and treated as a standard string.
=> Change param to string value for template

src/schema.ts, test/datafileobject/data.json, test/datafileobject/datafileobject.test.ts
In #190 , some behaviors with schemas were changed. This resulted in a new error when queries were made against schemas with no data associated with them in App Interface. We would receive errors like so:
```
`error` returned with GraphQL response {'message': "Cannot read properties of undefined (reading 'filter')", 'locations': [{'line': 2, 'column': 3}], 'path': ['external_users'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}
`error` returned with GraphQL response {'message': "Cannot read properties of undefined (reading 'filter')", 'locations': [{'line': 9, 'column': 3}], 'path': ['zones'], 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}
`error` returned with GraphQL response {'message': "Cannot read properties of undefined (reading 'filter')", 'locations': [{'line': 2, 'column': …
```
=> Fix for errors when retrieving a schema without a data file associated

src/schema.ts, test/server.test.ts
`null` was being used to do value match on datafile fields, this makes typed query hard because it requires a template to render conditional filter. For example [AWS_ACCOUNTS_QUERY](https://github.com/app-sre/qontract-reconcile/blob/344a8026c3cca7ad00f36f3846cfff90b7d61ba8/reconcile/queries.py#L458-L467).
This change allows `null` to be ignored so a single `gql` file with args always populated will be enough.
=> Ignore null as args value for searchable fields

package.json, src/db.ts, yarn.lock
Use built-in [crypto.createHash](https://nodejs.org/docs/latest-v16.x/api/crypto.html#cryptocreatehashalgorithm-options) to do sha256 calculation, one less dependency.
=> Replace node-forge with built-in crypto module

.eslintrc.json, package.json, src/db.ts, src/logger.ts, src/metrics.ts, src/schema.ts, src/server.ts, src/syntheticBackRefTrie.ts, test/datafileobject/datafileobject.test.ts, test/diff/diff.test.ts, test/multishas/multishas.test.ts, test/resourceref/resourceref.test.ts, test/schemas/schemas.test.ts, test/server.test.ts, test/synthetic/synthetic.test.ts, tslint.json, yarn.lock
TSLint has been deprecated as of 2019, [link](https://palantir.github.io/tslint/).
This replacement is mainly followed README from [tslint-config-airbnb](https://github.com/progre/tslint-config-airbnb).
Most changes are done by `yarn run lint-fix`, some changes are manually fixed by moving code around or simple cleanups, other not fixable changes are ignored like `// eslint-disable-line no-param-reassign`.
=> Use eslint to replace tslint

package.json, src/db.ts, src/metrics.ts, src/schema.ts, src/server.ts, src/syntheticBackRefTrie.ts, test/datafileobject/datafileobject.test.ts, test/diff/diff.test.ts, test/multishas/multishas.test.ts, test/resourceref/resourceref.test.ts, test/schemas/schemas.test.ts, test/server.test.ts, test/synthetic/synthetic.test.ts, yarn.lock
Current `"immutable": "^4.0.0-rc.12"` is outdated, since qontract-server is a read-only system, removing this package and replace it with built-in types, like `Map`, `Set`, `Array`.
Heap memory dropped about 20 MB after deletion, no obvious change in query performance (~10ms faster).
=> Remove immutable.js

README.md, src/server.ts
`dotenv` package is installed but not used correctly, missing `import`. This change fixed usage and updated README.
Now `npx depcheck` show `No depcheck issue`.
=> Fix dotenv usage

src/schema.ts, test/filter/data.json, test/filter/filter.test.ts
searchable fields can be used for filtering but only one value can be given at a time.
this PR adds support for basic filter object support. 
this exmple shows an `in` condition that allows us to filter objects based on a list of identifiers.
```gql
query SelfServiceRolesQuery {
roles: roles_v1(filter: {
name: {in: ["my-role", "my-other-role"]}
}) {
name
}
}
```
additionally the filter object can also be used for field and array equality
```gql
query SelfServiceRolesQuery {
roles: roles_v1(filter: {
name: "a name",
list_field: ["A", "B"]
}) {
name
}
}
```
`null` handling is different from the existing searchable field behaviour. the following example expects `some_optional_field` to be really null instead of ignoring the filter.
```gql
query SelfServiceRolesQuery {
roles: roles_v1(filter: …
```
=> list based filtering on searchable fields

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
part of https://issues.redhat.com/browse/APPSRE-8662
with the switch to using the endpoint internally (within the namespace), the router metrics no longer apply.
=> update dashboard to use service metrics

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
part of https://issues.redhat.com/browse/APPSRE-8662
following up on #213, the route variable is no longer used.
=> remove route templating variable

README.md, src/schema.ts, test/filter/data.json, test/filter/filter.test.ts
based on the filtering functionality introduced in https://github.com/app-sre/qontract-server/pull/209, this PR adds new filtering capabilities for nested objects.
reminder: the filtering functionality currently present was designed after [dgraphs filtering proposal](https://dgraph.io/docs/graphql/queries/search-filtering/), so basically via an argument called `filter`, e.g.
* filter based on an attributes value `filter: { name: "some name" }`
* filter on list membership `filter: { names: { in: ['name one", "name two" ] } }`
this `filter` argument was applicable only to top level fields of a GQL type, but now it can be applied to filter on nested objects by nesting `filter`s
this example query will return information for clusters of a specific organization. the `filter` argument is nested …
=> filtering for nested data

README.md, src/schema.ts, test/filter/filter.test.ts
following up on https://github.com/app-sre/qontract-server/pull/215, this PR introduces a filter predicate to check for not-equal, including null.
```json
"filter": {
"my_field": {
"ne": "my_value"
}
}
```
```json
"filter": {
"my_field": {
"ne": null
}
}
```
part of https://issues.redhat.com/browse/APPSRE-8502
=> non-equal filter predicate

README.md, test/filter/filter.test.ts
Nested filter used on array field in the middle is undefined, so document it here to avoid misuse. Based on https://github.com/app-sre/qontract-server/pull/215
=> Document nested filter limitations

openshift/app-interface.autoscale.yaml
Based on [Custom Metrics Autoscaler](https://docs.openshift.com/container-platform/4.16/nodes/cma/nodes-cma-autoscaling-custom.html), by default auto scale on 80% cpu utilization.
The reason cpu metrics is picked to scale is qontract server host all data in memory, when more request served, more cpu will be used to calculate graphql response.
Memory usage can also raise, but there are some memory leak issues due to the way we setup multiple bundles serving and outdated packages, it can't be used to autoscale as memory can't drop back to the baseline after request done.
Also adjusted default replicas to 3 and default resources to have same amount of memory request and limit.
[APPSRE-10762](https://issues.redhat.com/browse/APPSRE-10762)
=> Add autoscale openshift template

openshift/app-interface.autoscale.yaml, openshift/app-interface.yaml
Lets allow to set optional pull secrets as we do for github-mirror https://github.com/app-sre/github-mirror/blob/7ec5f47db6712c784bac0b38896e5fbfeec71b52/openshift/github-mirror.yaml#L20
Currently Konflux repos are always private ( https://issues.redhat.com/browse/RELEASE-1152).
In order to make a repository public, we need to submit a manual request to the Konflux team. We are in the process of integrating all repos and compiling a list that we will submit to them.
Until then, we can already start to optionally pull from private repo. Having this option doesnt harm.
=> APPSRE-10953 optional pull secrets

.tekton/qontract-server-master-push.yaml, Dockerfile, Makefile
Making qontract-server konflux compliant.
Lets have a dedicated explicit prod target that is explicitly used by konflux (and ci.ext for now). 
Also bump to ubi9
Further, the `nodejs-18-minimal` fails for sbom generation stage and non minimal image fails deprecation check:
```
[FAILURE] Image registry.access.redhat.com/ubi9/nodejs-18 has been deprecated
```
New nodejs-20-minimal image also fails sbom generation check:
```
AssertionError: Cannot get information about base image registry.access.redhat.com/ubi9/nodejs-20-minimal mentioned in the Dockerfile!
```
Using non-minimal image for now to get compliant build.
Running image locally works
```
make docker-run
(node:1) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on …
```
=> APPSRE-11019 updates and explicit prod build target
