app-sre/qontract-server

.env.example, graphql-schemas/base.js, graphql-schemas/bot.js, graphql-schemas/cluster.js, graphql-schemas/entity.js, graphql-schemas/permission.js, graphql-schemas/user.js, graphql-schemas/vaultSecret.js, models/db.js, openshift/app-interface.yaml, server.js
This PR depends on: https://github.com/app-sre/qontract-server/pull/2
=> Add local provider

models/db.js, package-lock.json, package.json, server.js
This PR depends on https://github.com/app-sre/qontract-server/pull/8, and must be rebased afterwards.
=> Add GET /sha256 and data presence check

graphql-schemas/base.js, graphql-schemas/bot.js, graphql-schemas/permission.js, graphql-schemas/quay-org.js, schemas/access/permission-1.yml, schemas/dependencies/quay-org-1.yml, server.js
=> Adds `dependencies/quay-org-1.yml` schema

assets/schema.yml, assets/schemas/app-sre/app-1.yml, assets/schemas/openshift/cluster-1.yml, assets/schemas/openshift/namespace-1.yml, src/db.ts, src/schema.ts, test/schemas/cluster.data.json, test/schemas/cluster.test.ts, test/server.data.json, test/server.test.ts
It also pluralizes the top-level queries.
=> Add resources query

openshift/app-interface.yaml
This PR adds a new sidecar which watches the data.json file on S3 for changes, and triggers a reload if any changes happen.
=> Add s3-reload sidecar

Makefile
to start a dev server in a container, use `make dev`.
to exit, Ctrl+z.
=> add dev command to Makefile

src/db.ts, src/server.ts
depends on https://github.com/app-sre/qontract-validator/pull/16
=> expose git-commit from bundle

Makefile
Signed-off-by: Amador Pahim <apahim@redhat.com>
=> Add app-interface commit to the "make bundle"

src/logger.ts, src/server.ts
This fixes PR #91 which was merged with some errors
=> Fixes logging

openshift/app-interface.yaml
=> Add affinity rules to openshift deployment

Makefile
Signed-off-by: Amador Pahim <apahim@redhat.com>
=> Adding GIT_COMMIT_TIMESTAMP

README.md, src/db.ts, src/server.ts, test/server.data.json, test/server.test.ts
part of https://issues.redhat.com/browse/APPSRE-2610
follow up on https://github.com/app-sre/qontract-validator/pull/23
=> expose git-commit-timestamp

Dockerfile
part of https://issues.redhat.com/browse/APPSRE-2821
=> Dockerfile pull from centos/centos

src/schema.ts, test/graphql_schema.json, test/schemas/schemas.data.json, test/server.data.json, test/server.test.ts
xref: https://github.com/app-sre/qontract-validator/pull/25
=> We return schema with resources

openshift/app-interface.yaml
=> Add PodDisruptionBudget

pr_check.sh
- Adding execution permission to pr_check.sh
- Installing yarn and its dependencies with npm for Jenkins executor
=> APPSRE-3783: Correcting pr_check.sh

Makefile
Add CONTAINER_ENGINE variable, with docker as default
to not break existing usages
=> Add CONTAINER_ENGINE variable

Makefile
on Mac + podman (via podman machine) , we have to export CONTAINER_SELINUX_FLAG=""
=> make reload + CONTAINER_SELINUX_FLAG

src/server.ts
this way the bundles can be regularly queried and not just used for diff calculation
follows up on https://github.com/app-sre/qontract-server/pull/138
=> register all INIT_DISK_BUNDLES as regular apolloservers

openshift/app-interface.yaml
Part one of migration to `Deployment` workload.
Ticket: https://issues.redhat.com/browse/APPSRE-5932
=> Provision deployment alongside deploymentconfig

Makefile
Title says it all. There is no reason this should delete all containers.
=> Makefile should not blindly delete all containers

SCHEMA.md
see https://github.com/app-sre/qontract-schemas/pull/237 and https://github.com/app-sre/qontract-validator/pull/42 for more details
=> add schema document for the isContextUnique attribute

openshift/app-interface.yaml
So that we can freely set or not any request/limit we need.
=> Make resources truly configurable

openshift/app-interface.yaml
follow-up to https://github.com/app-sre/qontract-server/pull/169
this will cause services to add deployment pods as endpoints
=> adjust service selectors to target deployment as well

openshift/app-interface.yaml
Tickets: 
* https://issues.redhat.com/browse/APPSRE-6334
* https://issues.redhat.com/browse/APPSRE-6336
* https://issues.redhat.com/browse/APPSRE-6337
Note: these 3 alerts are replicated across other environments in which qontract-server is deployed.
=> Add probes and service account to address dvo alerts

openshift/app-interface.yaml
addresses https://issues.redhat.com/browse/APPSRE-6347
=> Assign app-specific service account

Dockerfile, Dockerfiletest, pr_check.sh
Use multi-stage `Dockerfile` to merge `Dockerfile` and `Dockerfiletest`.
Signed-off-by: Di Wang <dwan@redhat.com>
=> Refactor docker build with multi-stage Dockerfile

openshift/app-interface.yaml
https://issues.redhat.com/browse/APPSRE-6954
Update OpenShift template to allow for optional authless setup with nginx-gate. 
Corresponding nginx-gate update: https://github.com/app-sre/nginx-gate/pull/8
=> APPSRE-6954 - optional authless nginx-gate

Dockerfile, package.json
Upgrade to node 18 as node 16 will be EOL at 2023-09-11
https://nodejs.dev/en/about/releases/
=> Upgrade node version to 18

src/server.ts, test/datafileobject/datafileobject.test.ts, test/diff/diff.test.ts, test/resourceref/resourceref.test.ts, test/schemas/schemas.test.ts, test/server.test.ts
`undefined` can't be used in `for...of` but works in `for...in`, to avoid ambiguity, fixed `restricted-syntax` by replacing it with `forEach` with a default `[]` null check.
Also check if bundle exist, return 404 when not found.
Some tests cleanup.
=> Fix undefined is not iterable and 404 issue

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
We're migrating the service to different clusters.
Related to APPSRE-7185
=> More available datasources

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
=> Restrict datasources to where q-s actually runs

package.json, yarn.lock
Maintenance on dev dependencies.
=> [Maintenance] Bump dev dependencies

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
=> add appsrep09ue1 to grafana datasource

openshift/app-interface.yaml
Related APPSRE-9925
Based on the discussion in https://github.com/app-sre/nginx-gate/pull/10#discussion_r1609163979
=> Add volume for nginx-gate for read-only mode

README.md, openshift/app-interface.yaml
part of https://issues.redhat.com/browse/APPSRE-10734
also includes a doc update to use plural.
previous art: #146
=> [openshift] optionally load init bundles from ConfigMap

openshift/app-interface.autoscale.yaml
Fix indentation of https://github.com/app-sre/qontract-server/pull/223
=> Fix scaled object indentation

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
* Add `env` to select prometheus for different environments.
* Update namespace to include `sre-capabilities-.*`
* Migrate panels for new grafana version.
=> Update grafana dashboard

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
=> update db for appsres11ue1 qs migration

Makefile
https://issues.redhat.com/browse/APPSRE-11018
=> use new official build of qontract-validator

grafana-dashboards/grafana-dashboard-qontract-server.configmap.yaml
=> update dashboard for q-s migration

.tekton/qontract-server-master-pull-request.yaml, Dockerfile
- use minimal image
- build prod stage on pr pipeline too
=> APPSRE-11019 minimal image

Makefile
=> Fix IMAGE_NAME
